import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';

import { payRuleSchema, type PayRule } from '@/domain/entities';
import { useRepositories } from '@/features/shifts/hooks/use-repositories';
import { AppScreen, DateField, EmptyState, FormField, PrimaryButton, SecondaryButton, TimeField } from '@/shared/components';
import { useTranslation } from '@/shared/i18n';
import { radius, spacing, typography, useAppTheme } from '@/shared/theme';
import { createId } from '@/shared/utils/id';
import { parseCurrencyToMinor, parsePercentageToBasisPoints } from '@/shared/utils/money';

type RuleKind = 'multiplier' | 'night' | 'weekend' | 'holiday' | 'threshold' | 'fixedBonus' | 'travel' | 'minimum' | 'dateOverride';
const kinds: RuleKind[] = ['multiplier', 'night', 'weekend', 'holiday', 'threshold', 'fixedBonus', 'travel', 'minimum', 'dateOverride'];

export default function PayRulesScreen() {
  const { profileId = '' } = useLocalSearchParams<{ profileId: string }>(); const repositories = useRepositories(); const { colors } = useAppTheme(); const { isRtl, t } = useTranslation();
  const [rules, setRules] = useState<PayRule[]>([]); const [editingId, setEditingId] = useState<string>(); const [kind, setKind] = useState<RuleKind>('multiplier'); const [name, setName] = useState('');
  const [value, setValue] = useState('125'); const [priority, setPriority] = useState('0'); const [startTime, setStartTime] = useState('22:00'); const [endTime, setEndTime] = useState('06:00');
  const [afterMinutes, setAfterMinutes] = useState('480'); const [specificDate, setSpecificDate] = useState(''); const [canStack, setCanStack] = useState(false); const [error, setError] = useState<string>();
  const [startWeekday, setStartWeekday] = useState('5'); const [endWeekday, setEndWeekday] = useState('6'); const [thresholdScope, setThresholdScope] = useState<'shift' | 'day'>('shift');
  const [thresholdBasis, setThresholdBasis] = useState<'net' | 'gross'>('net');
  const [effectiveFrom, setEffectiveFrom] = useState(''); const [effectiveTo, setEffectiveTo] = useState('');
  const refresh = useCallback(async () => setRules(await repositories.payRules.listForProfile(profileId)), [profileId, repositories.payRules]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  const save = async () => { try { const now = new Date().toISOString(); const numeric = Number(value); const isMultiplier = ['multiplier', 'night', 'weekend', 'holiday', 'threshold'].includes(kind); if (!Number.isFinite(numeric) || numeric <= 0 || (isMultiplier && numeric < 100)) throw new Error(t('rules.invalidMultiplier'));
    const conditions = kind === 'night' ? [{ type: 'timeWindow' as const, startTime, endTime }] : kind === 'weekend' ? [{ type: 'weekend' as const, startWeekday: Number(startWeekday), startTime, endWeekday: Number(endWeekday), endTime }] : kind === 'holiday' || kind === 'dateOverride' ? [{ type: 'date' as const, date: specificDate }] : kind === 'threshold' ? [{ type: 'workedMinutes' as const, afterMinutes: Number(afterMinutes), scope: thresholdScope, basis: thresholdBasis }] : [];
    const effect = kind === 'fixedBonus' ? { type: 'fixedBonus' as const, amountMinor: parseCurrencyToMinor(value) } : kind === 'travel' ? { type: 'reimbursement' as const, amountMinor: parseCurrencyToMinor(value) } : kind === 'minimum' ? { type: 'minimumPaidDuration' as const, minutes: Number(value) } : kind === 'dateOverride' ? { type: 'rateOverride' as const, hourlyRateMinor: parseCurrencyToMinor(value) } : { type: 'multiplier' as const, basisPoints: parsePercentageToBasisPoints(value) };
    const existing = rules.find((item) => item.id === editingId);
    const rule = payRuleSchema.parse({ id: editingId ?? createId('pay-rule'), salaryProfileId: profileId, name, priority: Number(priority), conditions, effect, canStack, isEnabled: existing?.isEnabled ?? true, effectiveFrom: effectiveFrom || undefined, effectiveTo: effectiveTo || undefined, createdAt: existing?.createdAt ?? now, updatedAt: now }); await repositories.payRules.save(rule); reset(); setError(undefined); await refresh();
  } catch (caught) { setError(caught instanceof Error && caught.message === t('rules.invalidMultiplier') ? caught.message : t('salary.invalidForm')); } };
  const reset = () => { setEditingId(undefined); setName(''); setKind('multiplier'); setValue('125'); setPriority('0'); setStartTime('22:00'); setEndTime('06:00'); setAfterMinutes('480'); setSpecificDate(''); setCanStack(false); setStartWeekday('5'); setEndWeekday('6'); setThresholdScope('shift'); setThresholdBasis('net'); setEffectiveFrom(''); setEffectiveTo(''); };
  const edit = (rule: PayRule) => { const condition = rule.conditions[0]; const nextKind: RuleKind = rule.effect.type === 'fixedBonus' ? 'fixedBonus' : rule.effect.type === 'reimbursement' ? 'travel' : rule.effect.type === 'minimumPaidDuration' ? 'minimum' : rule.effect.type === 'rateOverride' ? 'dateOverride' : condition?.type === 'timeWindow' ? 'night' : condition?.type === 'weekend' ? 'weekend' : condition?.type === 'date' ? 'holiday' : condition?.type === 'workedMinutes' ? 'threshold' : 'multiplier'; setEditingId(rule.id); setKind(nextKind); setName(rule.name); setPriority(String(rule.priority)); setCanStack(rule.canStack); setEffectiveFrom(rule.effectiveFrom ?? ''); setEffectiveTo(rule.effectiveTo ?? ''); setValue(rule.effect.type === 'multiplier' ? String(rule.effect.basisPoints / 100) : rule.effect.type === 'minimumPaidDuration' ? String(rule.effect.minutes) : rule.effect.type === 'rateOverride' ? String(rule.effect.hourlyRateMinor / 100) : String(rule.effect.amountMinor / 100)); if (condition?.type === 'timeWindow') { setStartTime(condition.startTime); setEndTime(condition.endTime); } if (condition?.type === 'weekend') { setStartWeekday(String(condition.startWeekday)); setStartTime(condition.startTime); setEndWeekday(String(condition.endWeekday)); setEndTime(condition.endTime); } if (condition?.type === 'date') setSpecificDate(condition.date); if (condition?.type === 'workedMinutes') { setAfterMinutes(String(condition.afterMinutes)); setThresholdScope(condition.scope); setThresholdBasis(condition.basis ?? 'net'); } };
  const toggle = async (rule: PayRule) => { await repositories.payRules.save({ ...rule, isEnabled: !rule.isEnabled, updatedAt: new Date().toISOString() }); await refresh(); };
  const changePriority = async (rule: PayRule, delta: number) => { await repositories.payRules.save({ ...rule, priority: rule.priority + delta, updatedAt: new Date().toISOString() }); await refresh(); };
  return <AppScreen title={t('rules.title')}>
    <SecondaryButton label={t('common.back')} onPress={() => router.back()} />
    <Text style={{ color: colors.textMuted, textAlign: isRtl ? 'right' : 'left' }}>{t('rules.explanation')}</Text>
    <View style={[styles.choices, { flexDirection: isRtl ? 'row-reverse' : 'row' }]}>{kinds.map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: kind === item }} key={item} onPress={() => setKind(item)} style={[styles.choice, { backgroundColor: colors.surface, borderColor: kind === item ? colors.primary : colors.border }]}><Text style={{ color: colors.text }}>{t(`rules.${item}` as Parameters<typeof t>[0])}</Text></Pressable>)}</View>
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>
      <FormField label={t('rules.name')} onChangeText={setName} value={name} /><FormField keyboardType="number-pad" label={t('rules.priority')} onChangeText={setPriority} value={priority} />
      {(kind === 'night' || kind === 'weekend') ? <><TimeField label={t('rules.startTime')} onChange={(next) => next && setStartTime(next)} value={startTime} /><TimeField label={t('rules.endTime')} onChange={(next) => next && setEndTime(next)} value={endTime} /></> : null}
      {kind === 'weekend' ? <><FormField keyboardType="number-pad" label={t('rules.startWeekday')} onChangeText={setStartWeekday} value={startWeekday} /><FormField keyboardType="number-pad" label={t('rules.endWeekday')} onChangeText={setEndWeekday} value={endWeekday} /></> : null}
      {kind === 'threshold' ? <><FormField keyboardType="number-pad" label={t('rules.afterMinutes')} onChangeText={setAfterMinutes} value={afterMinutes} /><View style={[styles.choices, { flexDirection: isRtl ? 'row-reverse' : 'row' }]}>{(['shift', 'day'] as const).map((scope) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: thresholdScope === scope }} key={scope} onPress={() => setThresholdScope(scope)} style={[styles.choice, { backgroundColor: colors.surface, borderColor: thresholdScope === scope ? colors.primary : colors.border }]}><Text style={{ color: colors.text }}>{t(scope === 'shift' ? 'rules.scopeShift' : 'rules.scopeDay')}</Text></Pressable>)}</View><View style={[styles.choices, { flexDirection: isRtl ? 'row-reverse' : 'row' }]}>{(['net', 'gross'] as const).map((basis) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: thresholdBasis === basis }} key={basis} onPress={() => setThresholdBasis(basis)} style={[styles.choice, { backgroundColor: colors.surface, borderColor: thresholdBasis === basis ? colors.primary : colors.border }]}><Text style={{ color: colors.text }}>{t(basis === 'net' ? 'rules.basisNet' : 'rules.basisGross')}</Text></Pressable>)}</View></> : null}
      {kind === 'dateOverride' || kind === 'holiday' ? <DateField label={t('rules.specificDate')} onChange={(next) => next && setSpecificDate(next)} value={specificDate || undefined} /> : null}
      <DateField label={t('salary.effectiveFrom')} onChange={(next) => setEffectiveFrom(next ?? '')} optional value={effectiveFrom || undefined} /><DateField label={t('salary.effectiveTo')} onChange={(next) => setEffectiveTo(next ?? '')} optional value={effectiveTo || undefined} />
      <FormField keyboardType="decimal-pad" label={t('rules.value')} onChangeText={setValue} value={value} />
      {(kind === 'multiplier' || kind === 'night' || kind === 'weekend' || kind === 'holiday' || kind === 'threshold') ? <View style={[styles.switchRow, { flexDirection: isRtl ? 'row-reverse' : 'row' }]}><Text style={{ color: colors.text, flex: 1 }}>{t('rules.stack')}</Text><Switch accessibilityLabel={t('rules.stack')} accessibilityRole="switch" value={canStack} onValueChange={setCanStack} /></View> : null}
      {error ? <Text accessibilityRole="alert" style={{ color: colors.danger }}>{error}</Text> : null}<PrimaryButton disabled={!profileId || !name.trim()} label={editingId ? t('common.save') : t('rules.add')} onPress={() => void save()} />{editingId ? <SecondaryButton label={t('common.cancel')} onPress={reset} /> : null}
    </View>
    {!rules.length ? <EmptyState title={t('rules.empty')} body={t('rules.explanation')} /> : rules.map((rule) => <View key={rule.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.text, textAlign: isRtl ? 'right' : 'left' }]}>{rule.name}</Text><Text style={{ color: colors.textMuted }}>{rule.isEnabled ? t('rules.enabled') : t('rules.disabled')} · {rule.priority}</Text><View style={[styles.switchRow, { flexDirection: isRtl ? 'row-reverse' : 'row' }]}><Text style={{ color: colors.text }}>{t('rules.enabled')}</Text><Switch accessibilityLabel={`${t('rules.enabled')} ${rule.name}`} value={rule.isEnabled} onValueChange={() => void toggle(rule)} /></View><SecondaryButton label={t('common.edit')} onPress={() => edit(rule)} /><SecondaryButton label={t('rules.priorityUp')} onPress={() => void changePriority(rule, 1)} /><SecondaryButton label={t('rules.priorityDown')} onPress={() => void changePriority(rule, -1)} /><SecondaryButton destructive label={t('common.delete')} onPress={() => void repositories.payRules.delete(rule.id).then(refresh)} /></View>)}
  </AppScreen>;
}
const styles = StyleSheet.create({ card: { borderRadius: radius.lg, borderWidth: StyleSheet.hairlineWidth, gap: spacing.sm, padding: spacing.md }, choices: { flexWrap: 'wrap', gap: spacing.xs }, choice: { borderRadius: radius.pill, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: spacing.md }, switchRow: { alignItems: 'center', justifyContent: 'space-between', minHeight: 48 }, title: { fontSize: typography.title, fontWeight: '800' } });
